config/routes.rb
Rails.application.routes.draw do
  root 'attendees#index'
  resources :attendees, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  validates :firstname, presence: true, length: {maximum: 60}
  validates :lastname, presence: true, length: {maximum: 60}
  validates :email, presence: true
  validates :phone, presence: true
  validates :company, presence: true
  validates :role, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController

  def index
  end

  def new
    @attendee = Attendee.new
  end

  def create
    @attendee = Attendee.create (attendee_params)
    if @attendee.invalid?
      flash[:error] = "Your registration could not be saved as the information you entered was invalid. Please try again."
    end
    redirect_to attendee_path(@attendee) #redirect to show page with persons details
  end

  def show
    @attendee = Attendee.find(params[:id])
  end 


  private

  def attendee_params
    params.require(:attendee).permit(:firstname, :lastname, :email, :phone, :company, :role)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/views/attendees/index.html.erb
<div class = "registration_box col-10 offset-1">
  <h1 class = "text-center"> Welcome to the 5th Annual Code Conference </h1>
  <br />
  <h2 class = "text-center"><%= link_to 'Register here', new_attendee_path, class: 'btn btn-warning btn-lg' %></h2>

</div>

app/views/attendees/new.html.erb
<div class = "registration_box col-8 offset-2">
  <div class = "col-10 offset-1">
    <%= simple_form_for @attendee do |f| %>
      <%= f.input :firstname, placeholder: 'e.g. John', error: 'First name is mandatory.' %>
      <%= f.input :lastname, placeholder: 'e.g. Smith', error: 'Last name is mandatory.' %>
      <%= f.input :email, placeholder: 'e.g. attendee@codeconference.com', error: 'Email is mandatory.' %>      
      <%= f.input :phone, placeholder: 'e.g. +1-242-555-5555' %>
      <%= f.input :company, placeholder: 'e.g. Coders FX' %>
      <%= f.input :role, placeholder: 'e.g. Rails Engineer' %>
      <div class = "row">
        <%= f.submit 'Register', class: "btn btn-success" %> 
        &nbsp &nbsp
        <%= link_to 'Back to Home', root_path, class: "btn btn-warning" %>
      <% end %>
    </div>
    
  </div>
</div>

app/views/attendees/show.html.erb
<div class = "registration_box col-10 offset-1">
  <h3 class = "text-center"> Your Registration Verification </h3>
  <br />

  <h6 class = "text-center"> Congratulations! Your registration was successful! </h6>
  <br/>

  <div class = "grey-box col-6 offset-3">
    <p> Registration Number: <strong><%= @attendee.id %></strong> </p>
    <p> Full Name: <strong> <%= @attendee.firstname %>  <%= @attendee.lastname%> </strong> </p>
    <p> Email Address: <strong> <%= @attendee.email %> </strong> </p>
    <p> Phone Number: <strong> <%= @attendee.phone %> </strong></p>
    <p> Company & Role: <strong> <%= @attendee.role %> at <%=@attendee.company %></strong> </p>
  </div>

  <br />
  <h6 class = "text-center"> <strong><i> Please print this for your records. </i></strong></h6>
  <br />
  <div class = "text-center">
    <%= link_to 'Back to Home', root_path, class: "btn btn-warning" %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codeconference</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= yield %>
  </body>
</html>